[package]
name = "bop-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alloy-primitives.workspace = true
op-alloy-rpc-types-engine.workspace = true
alloy-rpc-types.workspace = true

crossbeam-channel.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true

serde.workspace = true
thiserror.workspace = true
eyre.workspace = true
chrono.workspace = true
quanta.workspace = true
directories.workspace = true
shared_memory.workspace = true


jsonrpsee.workspace = true

[dev-dependencies]
serde_json.workspace = true
