optimism_package:
  chains:
    - participants:
        # Vanilla Stack (OP-Node, OP-EL) for the Sequencer
        - el_type: op-reth
          cl_type: op-node
          cl_image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest
        # Follower Node Stack (BOP-Node, BOP-EL)
        - el_type: op-geth
          el_image: based_op_geth
          el_extra_params:
            - --rollup.sequencerhttp
            - http://host.docker.internal:9997
          cl_type: op-node
          cl_image: based_op_node
          cl_extra_params:
            - --rpc.enable-based
      mev_type: based-portal
      mev_params:
        based_portal_image: based_portal_local
        builder_host: "172.17.0.1"
        builder_port: "9997"
      additional_services:
        - blockscout

ethereum_package:
  participants:
    - el_type: geth
      # This is fixed because v1.15.0 (latest) introduces braking changes
      el_image: ethereum/client-go:v1.14.13
