optimism_package:
  chains:
    - participants:
        - el_type: op-reth
          cl_type: op-node
          # cl_extra_params: [--rpc.based]
      mev_type: based-portal
      mev_params:
        based_portal_image: based_portal_local
        builder_host: "172.17.0.1"
        builder_port: "9997"
      additional_services:
        - blockscout

ethereum_package:
  participants:
    - el_type: geth
      el_image: ethereum/client-go:v1.14.13
